export interface Product {
  id: string
  name: string
  brand: string
  category: string
  price: number
  imageUrl: string
  description?: string
  isFeatured?: boolean
  stock?: number
  brandId?: string
  categoryId?: string
  salePrice?: number
  volume?: string
  gender?: string
  scentFamily?: string
  topNotes?: string
  middleNotes?: string
  baseNotes?: string
  longevity?: string
  sillage?: string
  brandOrigin?: string
  concentration?: string
  season?: string
  scentMood?: string
  productType?: string
  style?: string
  releaseYear?: string
  isActive?: boolean
  brandName?: string
  categoryName?: string
}